FROM node:18.16.0 AS builder

WORKDIR /app/client/

COPY . .

RUN npm install --progress=plain

RUN npm run build --progress=plain

FROM nginx:latest

COPY --from=builder /app/client/dist /usr/share/nginx/html

WORKDIR /etc/nginx/

COPY client/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 8080