FROM node:18.16.0 AS builder

WORKDIR /app/client

COPY /client /app/client

RUN npm install

RUN npm run build

FROM nginx:latest

COPY --from=builder /app/client/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 5173