version: '2'

services:
  frontstage:
    build:
      context: .
      dockerfile: ./client/dockerfile
    image: front:dev1
    container_name: front_dev
    ports:
      - "88:80"
    networks:
      - networkdev
    volumes:
      - /home/larry/log/error:/var/log/nginx/1/
      - /home/larry/log/access_log:/var/log/nginx/2/
  backstage:
    build:
      context: .
      dockerfile: ./server/dockerfile
    image: back:dev1
    container_name: back_dev
    ports:
      - "8088:8080"
    networks:
      - networkdev
    depends_on:
      - frontstage
  dbstage:
    image: postgres:latest 
    ports:
      - "5438:5432"
    env_file:
      - .env
    networks:
      - networkdev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  networkdev:
    driver: bridge