version: '2'

services:
  frontprod:
    build:
      context: .
      dockerfile: ./client/dockerfile
    image: front:1
    container_name: front_main
    ports:
      - "80:80"
    networks:
      - networkmain
    volumes:
      - /home/larry/log/error:/var/log/nginx/1/
      - /home/larry/log/access_log:/var/log/nginx/2/
  backprod:
    build:
      context: .
      dockerfile: ./server/dockerfile
    image: back:1
    container_name: back_main 
    ports:
      - "8080:8080"
    networks:
      - networkmain
    depends_on:
      - frontprod
  dbrod:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - networkmain
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  networkmain:
    driver: bridge