version: '2'

services:
  front:
    build:
      context: .
      dockerfile: ./client/dockerfile
    image: front:1
    ports:
      - "8080:8080"
    networks:
      - networkdev
    volumes:
      - /home/larry/log/error:/var/log/nginx/1/
      - /home/larry/log/access_log:/var/log/nginx/2/
  back:
    build:
      context: .
      dockerfile: ./server/dockerfile
    image: back:1
    ports:
      - "80:80"
    networks:
      - networkdev
    depends_on:
      - front
  db:
    image: postgres:latest 
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - networkdev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  networkdev:
    driver: bridge